/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import business.Apartamento;
import java.awt.Color;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.HashMap;

/**
 *
 * @author marioferreira
 */
public class ConsultarDespesa extends javax.swing.JFrame {
    HashMap<String,Apartamento> app;
    Apartamento apart;
    Integer despesa;
    Integer tipo=-1;

    /**
     * Creates new form ConsultarDespesa
     */
    public ConsultarDespesa(HashMap<String,Apartamento>b,Apartamento a, Integer d, Integer tipo) {
        this.app=b;
        this.apart = a;
        this.despesa = d;
        this.tipo = tipo;
        initComponents();
        nomeLabel.setText(this.apart.getDespesas().get(d).getNome());
        descricaoLabel.setText(this.apart.getDespesas().get(d).getDescricao());
        valorLabel.setText(Float.toString(this.apart.getDespesas().get(d).getValor()));
        Format formatter = new SimpleDateFormat("dd/mm/yyyy");
        String date = formatter.format(this.apart.getDespesas().get(d).getPrazo());
        dataLabel.setText(date);
       
            entidadeLabel.setText(Integer.toString(this.apart.getDespesas().get(d).getEntidade()));
            referenciaLabel.setText(Integer.toString(this.apart.getDespesas().get(d).getReferencia()));
            if (this.apart.getDespesas().get(d).getEstado()==0) {
                pagoLabel.setText("Não");
                pagoLabel.setForeground(new Color(200, 0, 0));
            }
            else {
                pagoLabel.setText("Sim");
                pagoLabel.setForeground(new Color(10, 200, 10));
            }
        
       
        String mor="";
  
        
        //moradoresLabel.setText(mor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        valorLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dataLabel = new javax.swing.JLabel();
        dadosLabel = new javax.swing.JLabel();
        entidade1Label = new javax.swing.JLabel();
        referencia1Label = new javax.swing.JLabel();
        voltarButton = new javax.swing.JButton();
        editarButton = new javax.swing.JButton();
        entidadeLabel = new javax.swing.JLabel();
        referenciaLabel = new javax.swing.JLabel();
        descricaoLabel = new javax.swing.JLabel();
        pagarButton = new javax.swing.JButton();
        pago1Label = new javax.swing.JLabel();
        pagoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Consulta de Despesa");

        jLabel3.setText("Nome:");

        nomeLabel.setText("Uma despesa qualquer");

        jLabel5.setText("Descrição:");

        jLabel7.setText("Valor:");

        valorLabel.setText("0.0");

        jLabel9.setText("Data Limite:");

        dataLabel.setText("00/00/0000");

        dadosLabel.setText("Dados de pagamento:");

        entidade1Label.setText("Entidade:");

        referencia1Label.setText("Referência:");

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        editarButton.setText("Editar");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        entidadeLabel.setText("10349");

        referenciaLabel.setText("304919491");

        descricaoLabel.setText("nao faço ideia");

        pagarButton.setText("Registar Pagamento");
        pagarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarButtonActionPerformed(evt);
            }
        });

        pago1Label.setText("Pago:");

        pagoLabel.setText("Sim");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descricaoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 230, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(dataLabel)
                            .addComponent(jLabel9)
                            .addComponent(valorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(referencia1Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(referenciaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dadosLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(entidade1Label)
                                .addGap(18, 18, 18)
                                .addComponent(entidadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pago1Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pagoLabel)))
                        .addGap(45, 45, 45))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(181, 181, 181))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pagarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(voltarButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nomeLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(descricaoLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7)
                        .addGap(13, 13, 13)
                        .addComponent(valorLabel)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dataLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(dadosLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(entidade1Label)
                            .addComponent(entidadeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(referencia1Label)
                            .addComponent(referenciaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pago1Label)
                            .addComponent(pagoLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltarButton)
                    .addComponent(editarButton)
                    .addComponent(pagarButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        ConsultarDespesas cd = new ConsultarDespesas (this.app,this.apart);
        cd.setLocationRelativeTo(this);
        cd.setVisible(true);
        setVisible(false); //you can't see me!
        dispose(); 
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarButtonActionPerformed

    private void pagarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarButtonActionPerformed
        Pagamento p = new Pagamento (this.app,this.apart, this.despesa, this.tipo);
        p.setLocationRelativeTo(this);
        p.setVisible(true);
        setVisible(false); //you can't see me!
        dispose(); 
    }//GEN-LAST:event_pagarButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dadosLabel;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JLabel descricaoLabel;
    private javax.swing.JButton editarButton;
    private javax.swing.JLabel entidade1Label;
    private javax.swing.JLabel entidadeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JButton pagarButton;
    private javax.swing.JLabel pago1Label;
    private javax.swing.JLabel pagoLabel;
    private javax.swing.JLabel referencia1Label;
    private javax.swing.JLabel referenciaLabel;
    private javax.swing.JLabel valorLabel;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
