/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import business.Apartamento;
import business.Despesa;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;

/**
 *
 * @author marioferreira
 */
public class ConsultarDespesas extends javax.swing.JFrame {
    
    Apartamento apart;
    HashMap<String,Apartamento> app;
    HashMap<Integer,Despesa> ex;

    /**
     * Creates new form ConsultarDespesas
     */
    public ConsultarDespesas(HashMap<String,Apartamento> b, Apartamento a) {
        this.app=b;
        this.apart = a;
        this.ex = new HashMap<>();
        initComponents();
        updateList();
    }
    
    public ConsultarDespesas(HashMap<String,Apartamento> b, Apartamento a, HashMap<Integer,Despesa> c) {
        this.app=b;
        this.apart = a;
        this.ex = c;
        initComponents();
        updateList();
    }
    
    private void updateList() {
        String mail = this.apart.getMail();
        DefaultListModel <String> dlm = new DefaultListModel<String>();
        if(ex.isEmpty()){
        for(Map.Entry<Integer,Despesa>  entry : apart.getDespesas().entrySet()) {
            
            if (entry.getValue().getEstado()==0) {
                dlm.addElement(entry.getValue().getId()+" - N - "+entry.getValue().getNome());
            }
            else {
                dlm.addElement(entry.getValue().getId()+" - P - "+entry.getValue().getNome());
            }
        }
        }
        else{
            for(Map.Entry<Integer,Despesa>  entry : ex.entrySet()) {
            
            if (entry.getValue().getEstado()==0) {
                dlm.addElement(entry.getValue().getId()+" - N - "+entry.getValue().getNome());
            }
            else {
                dlm.addElement(entry.getValue().getId()+" - P - "+entry.getValue().getNome());
            }
        }
            
        }
        despesasList.setModel(dlm);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        despesasList = new javax.swing.JList<>();
        registExpenseButton = new javax.swing.JButton();
        consultExpenseLabel = new javax.swing.JLabel();
        consultExpenseButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        limparButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        despesasList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        despesasList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(despesasList);

        registExpenseButton.setText("Registar Despesa");
        registExpenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registExpenseButtonActionPerformed(evt);
            }
        });

        consultExpenseLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        consultExpenseLabel.setText("Consultar Despesas");

        consultExpenseButton.setText("Consultar Despesa");
        consultExpenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultExpenseButtonActionPerformed(evt);
            }
        });

        backButton.setText("Voltar");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        limparButton.setText("Default");
        limparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Filtrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(limparButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(consultExpenseLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(consultExpenseButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(registExpenseButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(26, 26, 26))
                    .addComponent(backButton, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(consultExpenseLabel)
                .addGap(50, 50, 50)
                .addComponent(consultExpenseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registExpenseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limparButton)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultExpenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultExpenseButtonActionPerformed
        String str = despesasList.getSelectedValue();
        if (str!=null) {
        String[] parts = str.split(" ");
        Integer d = Integer.parseInt(parts[0]);
        Despesa des = this.apart.getDespesas().get(d);
        ConsultarDespesa cd;
        if (des.getClass().getName().equals("business.Despesa"))
            cd = new ConsultarDespesa (this.app,this.apart, d, 1);
        else 
            cd = new ConsultarDespesa (this.app,this.apart, d, 0);
        cd.setLocationRelativeTo(this);
        cd.setVisible(true);
        setVisible(false); //you can't see me!
        dispose(); //Destroy the JFrame object
        }
    }//GEN-LAST:event_consultExpenseButtonActionPerformed

    private void registExpenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registExpenseButtonActionPerformed
          AdicionarDespesa ad = new AdicionarDespesa (this.app,this.apart, 1);
        ad.setLocationRelativeTo(this);
        ad.setVisible(true);
        setVisible(false); //you can't see me!
        dispose();
    }//GEN-LAST:event_registExpenseButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        MenuPrincipal m = new MenuPrincipal(this.app,this.apart.getPin());
        m.setLocationRelativeTo(this);
        m.setVisible(true);
        setVisible(false); //you can't see me!
        dispose(); //Destroy the JFrame object
    }//GEN-LAST:event_backButtonActionPerformed

    private void limparButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparButtonActionPerformed
       this.ex = new HashMap<>();
       updateList();
    }//GEN-LAST:event_limparButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Filtrar m = new Filtrar(this.app,this.apart);
        m.setLocationRelativeTo(this);
        m.setVisible(true);
        setVisible(false); //you can't see me!
        dispose(); //Destroy the JFrame object
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton consultExpenseButton;
    private javax.swing.JLabel consultExpenseLabel;
    private javax.swing.JList<String> despesasList;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limparButton;
    private javax.swing.JButton registExpenseButton;
    // End of variables declaration//GEN-END:variables
}
