/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import business.Apartamento;
import business.Despesa;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author Marcos
 */
public class Filtrar extends javax.swing.JFrame {

    HashMap<String,Apartamento> app;
    Apartamento apart;
    /**
     * Creates new form Filtrar
     */
    public Filtrar(HashMap<String,Apartamento> a, Apartamento b) {
        this.app=a;
        this.apart=b;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        EstadoField = new javax.swing.JTextField();
        DescriçaoField = new javax.swing.JTextField();
        TipoField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Filtrar por :");

        jLabel2.setText("Estado:");

        jLabel3.setText("Descriçao:");

        jLabel4.setText("Tipo");

        jButton1.setText("PreData");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("PosData");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Total");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        EstadoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(42, 42, 42)
                        .addComponent(EstadoField))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(50, 50, 50)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DescriçaoField)
                            .addComponent(TipoField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(34, 34, 34)
                                .addComponent(jButton2)
                                .addGap(42, 42, 42)
                                .addComponent(jButton3))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 69, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(EstadoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(DescriçaoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(TipoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          String estado = EstadoField.getText();
        String descricao = DescriçaoField.getText();
        String tipo = TipoField.getText();
        ArrayList<Integer> keys = new ArrayList<>();
        HashMap<Integer,Despesa> novo = this.apart.filterDataPre();
       if(estado.equals("P")) {
            for(Map.Entry<Integer, Despesa> i : novo.entrySet()){
                if ((i.getValue().getEstado())== 0) {
                    System.out.println(i.getKey());
                    //novo.remove(i.getKey());
                    keys.add(i.getKey());
                }
            }
            for (Integer key : keys) { 
                novo.remove(key);
            }
        }
        if(estado.equals("N")) {
            for(Map.Entry<Integer, Despesa> i : novo.entrySet()){
                if (i.getValue().getEstado()== 1) 
                keys.add(i.getKey());
            }
            for (Integer key : keys) { 
                novo.remove(key);
            }
        }
        keys = new ArrayList<>();
        for(Map.Entry<Integer, Despesa> i : novo.entrySet()){
            if(!(i.getValue().getDescricao().contains(descricao))) 
                keys.add(i.getKey());
        }
        for (Integer key : keys) { 
            novo.remove(key);
        }
        
        keys = new ArrayList<>();

        for(Map.Entry<Integer, Despesa> i : novo.entrySet()){
            if(!(i.getValue().getTipo().contains(tipo))) 
                keys.add(i.getKey());
        }
        
        for (Integer key : keys) {
            novo.remove(key);
        }
        
         ConsultarDespesas m = new ConsultarDespesas(app,apart,novo);
                m.setLocationRelativeTo(this);
                m.setVisible(true);
                setVisible(false); //you can't see me!
                dispose(); //Destroy the JFrame object
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EstadoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadoFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String estado = EstadoField.getText();
        String descricao = DescriçaoField.getText();
        String tipo = TipoField.getText();
        ArrayList<Integer> keys = new ArrayList<>();
        HashMap<Integer,Despesa> novo = this.apart.filterDataPos();
        if(estado.equals("P")) {
            for(Map.Entry<Integer, Despesa> i : novo.entrySet()){
                if ((i.getValue().getEstado())== 0) {
                    System.out.println(i.getKey());
                    //novo.remove(i.getKey());
                    keys.add(i.getKey());
                }
            }
            for (Integer key : keys) { 
                novo.remove(key);
            }
        }
        if(estado.equals("N")) {
            for(Map.Entry<Integer, Despesa> i : novo.entrySet()){
                if (i.getValue().getEstado()== 1) 
                keys.add(i.getKey());
            }
            for (Integer key : keys) { 
                novo.remove(key);
            }
        }
        keys = new ArrayList<>();
        for(Map.Entry<Integer, Despesa> i : novo.entrySet()){
            if(!(i.getValue().getDescricao().contains(descricao))) 
                keys.add(i.getKey());
        }
        for (Integer key : keys) { 
            novo.remove(key);
        }
        
        keys = new ArrayList<>();

        for(Map.Entry<Integer, Despesa> i : novo.entrySet()){
            if(!(i.getValue().getTipo().contains(tipo))) 
                keys.add(i.getKey());
        }
        
        for (Integer key : keys) {
            novo.remove(key);
        }
        
         ConsultarDespesas m = new ConsultarDespesas(app,apart,novo);
                m.setLocationRelativeTo(this);
                m.setVisible(true);
                setVisible(false); //you can't see me!
                dispose(); //Destroy the JFrame object
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String estado = EstadoField.getText();
        String descricao = DescriçaoField.getText();
        String tipo = TipoField.getText();
        ArrayList<Integer> keys = new ArrayList<>();
        HashMap<Integer,Despesa> novo = this.apart.getDespesas_copia();
        for(Map.Entry<Integer,Despesa> j : novo.entrySet()){
            System.out.println(j.getKey() + "ESTADO:" + j.getValue().getEstado());
        }
        if(estado.equals("P")) {
            for(Map.Entry<Integer, Despesa> i : novo.entrySet()){
                if ((i.getValue().getEstado())== 0) {
                    System.out.println(i.getKey());
                    //novo.remove(i.getKey());
                    keys.add(i.getKey());
                }
            }
            for (Integer key : keys) { 
                novo.remove(key);
            }
        }
        if(estado.equals("N")) {
            for(Map.Entry<Integer, Despesa> i : novo.entrySet()){
                if (i.getValue().getEstado()== 1) 
                keys.add(i.getKey());
            }
            for (Integer key : keys) { 
                novo.remove(key);
            }
        }
        keys = new ArrayList<>();
        for(Map.Entry<Integer, Despesa> i : novo.entrySet()){
            if(!(i.getValue().getDescricao().contains(descricao))) 
                keys.add(i.getKey());
        }
        for (Integer key : keys) { 
            novo.remove(key);
        }
        
        keys = new ArrayList<>();

        for(Map.Entry<Integer, Despesa> i : novo.entrySet()){
            if(!(i.getValue().getTipo().contains(tipo))) 
                keys.add(i.getKey());
        }
        
        for (Integer key : keys) {
            novo.remove(key);
        }
        
         ConsultarDespesas m = new ConsultarDespesas(app,apart,novo);
                m.setLocationRelativeTo(this);
                m.setVisible(true);
                setVisible(false); //you can't see me!
                dispose(); //Destroy the JFrame object
    }//GEN-LAST:event_jButton3ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DescriçaoField;
    private javax.swing.JTextField EstadoField;
    private javax.swing.JTextField TipoField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
