package presentation;

import business.Apartamento;
import java.awt.Color;
import java.util.HashMap;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author marioferreira
 */
public class MenuPrincipal extends javax.swing.JFrame {
    Apartamento apart;
    HashMap<String,Apartamento> app;
    
    /**
     * Creates new form MainWindow
     */
    public MenuPrincipal(HashMap<String,Apartamento> a , String pin) {
        this.app=a;
        this.apart = a.get(pin);
        initComponents();
        float balanco = this.apart.getMorador(this.apart.getMail()).getBalanco();
        debt1Label.setText(Float.toString(balanco));
        if (balanco>=0) 
            debt1Label.setForeground(new Color(10, 200, 10));
        else
            debt1Label.setForeground(new Color(200, 0, 0));
        System.out.println(this.apart.getMoradores().get(this.apart.getMail()).getAdmin());
        if (!this.apart.getMoradores().get(this.apart.getMail()).getAdmin()) 
            registarButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        debtLabel = new javax.swing.JLabel();
        expensesButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        menuLabel = new javax.swing.JLabel();
        debt1Label = new javax.swing.JLabel();
        registarButton = new javax.swing.JButton();
        DividaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        debtLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        debtLabel.setText("Balanço:");

        expensesButton.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        expensesButton.setText("Consultar Despesas");
        expensesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        expensesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expensesButtonActionPerformed(evt);
            }
        });

        profileButton.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        profileButton.setText("Consultar Perfil");
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });

        logoutButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        menuLabel.setFont(new java.awt.Font("Razer Header Light", 0, 24)); // NOI18N
        menuLabel.setText("Menu Principal");

        debt1Label.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        debt1Label.setText("0");

        registarButton.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        registarButton.setText("Registar Morador");
        registarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registarButtonActionPerformed(evt);
            }
        });

        DividaButton.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        DividaButton.setText("Consultar Dividas");
        DividaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DividaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(debtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(debt1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DividaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(registarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(profileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(expensesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(debtLabel)
                            .addComponent(debt1Label)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 104, Short.MAX_VALUE)
                        .addComponent(expensesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DividaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.apart.setMail(null);
        Login l = new Login(this.app);
        l.setLocationRelativeTo(this);
        l.setVisible(true);
        setVisible(false); //you can't see me!
        dispose(); 
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void expensesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expensesButtonActionPerformed
        ConsultarDespesas cd = new ConsultarDespesas (this.app,this.apart);
        cd.setLocationRelativeTo(this);
        cd.setVisible(true);
        setVisible(false); //you can't see me!
        dispose(); 
    }//GEN-LAST:event_expensesButtonActionPerformed

    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
        Perfil p = new Perfil (this.app,this.apart);
        p.setLocationRelativeTo(this);
        p.setVisible(true);
        setVisible(false); //you can't see me!
        dispose();
    }//GEN-LAST:event_profileButtonActionPerformed

    private void registarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registarButtonActionPerformed
        Registar r = new Registar (this.app,this.apart);
        r.setLocationRelativeTo(this);
        r.setVisible(true);
        setVisible(false); //you can't see me!
        dispose(); 
    }//GEN-LAST:event_registarButtonActionPerformed

    private void DividaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DividaButtonActionPerformed
        ConsultarDividas cd = new ConsultarDividas (this.app,this.apart);
        cd.setLocationRelativeTo(this);
        cd.setVisible(true);
        setVisible(false); //you can't see me!
        dispose(); 
                   
    }//GEN-LAST:event_DividaButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DividaButton;
    private javax.swing.JLabel debt1Label;
    private javax.swing.JLabel debtLabel;
    private javax.swing.JButton expensesButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JButton profileButton;
    private javax.swing.JButton registarButton;
    // End of variables declaration//GEN-END:variables
}
