/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import business.Apartamento;
import java.util.HashMap;

/**
 *
 * @author marioferreira
 */
public class TipoDespesa extends javax.swing.JFrame {
    HashMap<String,Apartamento>app;
    Apartamento apart;
    
    /**
     * Creates new form TipoDespesa
     */
    public TipoDespesa(HashMap<String,Apartamento> b,Apartamento a) {
        this.apart = a;
        this.app=b;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dinheiroButton = new javax.swing.JButton();
        mbButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Que tipo de despesa deseja adicionar?");

        dinheiroButton.setText("Dinheiro");
        dinheiroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dinheiroButtonActionPerformed(evt);
            }
        });

        mbButton.setText("MultiBanco");
        mbButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbButtonActionPerformed(evt);
            }
        });

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dinheiroButton)
                        .addGap(18, 18, 18)
                        .addComponent(mbButton))
                    .addComponent(jLabel1))
                .addGap(79, 79, 79))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(voltarButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dinheiroButton)
                    .addComponent(mbButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(voltarButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dinheiroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dinheiroButtonActionPerformed
        AdicionarDespesa ad = new AdicionarDespesa (this.app,this.apart, 0);
        ad.setLocationRelativeTo(this);
        ad.setVisible(true);
        setVisible(false); //you can't see me!
        dispose();
    }//GEN-LAST:event_dinheiroButtonActionPerformed

    private void mbButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbButtonActionPerformed
        AdicionarDespesa ad = new AdicionarDespesa (this.app,this.apart, 1);
        ad.setLocationRelativeTo(this);
        ad.setVisible(true);
        setVisible(false); //you can't see me!
        dispose();
    }//GEN-LAST:event_mbButtonActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        ConsultarDespesas cd = new ConsultarDespesas (this.app,this.apart);
        cd.setLocationRelativeTo(this);
        cd.setVisible(true);
        setVisible(false); //you can't see me!
        dispose(); 
    }//GEN-LAST:event_voltarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dinheiroButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mbButton;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
